# This is a basic workflow that is manually triggered

name: integration_test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      result:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Success (true) or Failure (false)'
        # Default value if no value is explicitly provided
        default: false
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Failure
      if: ${{ inputs.result != true }}
      run: echo "Failure" && exit 1
    - name: Success
      if: ${{ inputs.result == true }}
      run: echo "Success" && exit 0
      
